### ISSUE TITLE
Add awesome-computercraft to Awesome meta-list

### ISSUE THREAD

**Issue by tomodachi94** [tomodachi94/awesome-computercraft#5]
Tracking issue for getting this list onto sindresorhus/awesome.

**Comment by tomodachi94** [comment]
Here's a checklist of the requirements:

- [x] Has been around for at least 30 days.
- [x] Run [awesome-lint](https://github.com/sindresorhus/awesome-lint) on your list and fix the reported issues. If there are false-positives or things that cannot/shouldn't be fixed, please [report it](https://github.com/sindresorhus/awesome-lint/issues/new).
- [x] The default branch should be named [main, not master](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/).
    - This was done automatically when the repository was created.
- [x] Includes a succinct description of the project/theme at the top of the readme. [(Example)](https://github.com/willempienaar/awesome-quantified-self)
- [x] It's the result of hard work and the best I could possibly produce. If you have not put in considerable effort into your list, your pull request will be immediately closed.
- [x] The repo name of your list should be in lowercase slug format: awesome-name-of-list.
- [x] The heading title of your list should be in [title case](https://capitalizemytitle.com/) format: # Awesome Name of List.
- [x] Non-generated Markdown file in a GitHub repo.
- [x] The repo should have awesome-list & awesome as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
- [x] Not a duplicate. Please search for existing submissions.
- [x] Only has awesome items. Awesome lists are curations of the best, not everything.
- [x] Does not contain items that are unmaintained, has archived repo, deprecated, or missing docs. If you really need to include such items, they should be in a separate Markdown file.
- [x] Includes a project logo/illustration whenever possible.
- [x] Either centered, fullwidth, or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
- [x] Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- [x] Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/main/awesome.md#awesome-badge).
- [x] Has a Table of Contents section.
- [x] Has an appropriate license.
- [x] Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/main/awesome.md#include-contribution-guid elines).
- [x] The file should be named contributing.md. Casing is up to you.
    - It can optionally be linked from the readme in a dedicated section titled Contributing, positioned at the top or bottom of the main content.
All non-important but necessary content (like extra copyright notices, hyperlinks to sources, pointers to expansive content, etc) should be grouped in a Footnotes section at the bottom of the readme. The section should not be present in the Table of Contents.
- [x] Has consistent formatting and proper spelling/grammar.
- [x] The link and description are separated by a dash.
    - Example: - [AVA](…) - JavaScript test runner.
    - I'm not sure what to do with this. The literature section follows this, but everything else has a bolded section at the end of the item.
- [x] The description starts with an uppercase character and ends with a period.
- [x] Consistent and correct naming. For example, Node.js, not NodeJS or node.js.
- [x] Doesn't use [hard-wrapping](https://stackoverflow.com/questions/319925/difference-between-hard-wrap-and-soft-wrap).
- [x] Doesn't include a Travis badge.
- [x] Doesn't include an Inspired by awesome-foo or Inspired by the Awesome project kinda link at the top of the readme. The Awesome badge is enough.

Super important when the PR gets created:
> **To verify that you've read all the guidelines, please comment on your pull request with just the word unicorn.**

**Comment by tomodachi94** [comment]
PR has been sitting for a few weeks now with no reply.

**Comment by tomodachi94** [comment]
See also: https://github.com/sindresorhus/awesome/pull/2405

**Comment by tomodachi94** [comment]
PR was merged.
